# All the slug prefixes from the S3 container. We can update these through Streamlit dash
mf_sales_url = "https://cvf-prod.s3.amazonaws.com/media/documents/2408ba86b34ff37c21d4461f6ba14f757cd9014afd4bf61ca3bc7005b88fb467.3a7190ca2475.xlsx"
mf_analyzer_url = "https://cvf-prod.s3.amazonaws.com/media/documents/3b498689123d800b55410e7ed5dc219a01b836ec277b43b29f33cf32089fd36e.a5fb2d987e31.xlsx"
vest_wholesaler_url = "https://cvf-prod.s3.amazonaws.com/media/documents/5ba4f0c299c5c2df09f05430e03bd9b8511176ee56ecd7dadd4e09d7f610b698.b6ca92030167.xlsx"
ft_wholesaler_url = "https://cvf-prod.s3.amazonaws.com/media/documents/47ae571678a1d3fbe67eef4500ac3c1c4ecdafb8d95bf4cfb7a4b8cc27af71a5.d22647780ced.xlsx"
etf_sales_url = "https://cvf-prod.s3.amazonaws.com/media/documents/cf07815e8d57fb7b2dd61f72a0b7b8fa9115383321a637672d9f0c56f4e10695.d017a02d469a.xlsx"
uit_sales_url = "https://cvf-prod.s3.amazonaws.com/media/documents/f468eb983edd0dcaa5a0ae66b3fd6835d5d75a0dd74ee6d0ae10ad1f03bdd81f.a151f4d50b5d.xlsx"
buffer_etf_tickers = ['BGLD',
'BUFD',
'BUFG',
'BUFQ',
'BUFR',
'BUFT',
'DAPR',
'DAUG',
'DDEC',
'DFEB',
'DJAN',
'DJUL',
'DJUN',
'DMAR',
'DMAY',
'DNOV',
'DOCT',
'DSEP',
'FAPR',
'FAUG',
'FDEC',
'FFEB',
'FJAN',
'FJUL',
'FJUN',
'FMAR',
'FMAY',
'FNOV',
'FOCT',
'FSEP',
'QDEC',
'QJUN',
'QMAR',
'QSPT',
'XDEC',
'XJUN',
'XSEP',
'YDEC',
'YJUN',
'YMAR',
'YSEP']
target_income_etf_tickers = ['KNG','IGLD','RDVI']