# All the slug prefixes from the S3 container. We can update these through Streamlit dash
master_territory_url = "https://cvf-prod.s3.us-west-2.amazonaws.com/media/documents/0e71be09c555ccd7231ab517b0e9d2b782b27a601d39074114148a233d52cc28.bf620790f620.csv"
mf_sales_url = "https://cvf-prod.s3.us-west-2.amazonaws.com/media/documents/2408ba86b34ff37c21d4461f6ba14f757cd9014afd4bf61ca3bc7005b88fb467.fb67014c4c01.xlsx"
mf_analyzer_url = "https://cvf-prod.s3.us-west-2.amazonaws.com/media/documents/3b498689123d800b55410e7ed5dc219a01b836ec277b43b29f33cf32089fd36e.bab6cd8ebeec.xlsx"
vest_wholesaler_url = "https://cvf-prod.s3.amazonaws.com/media/documents/5ba4f0c299c5c2df09f05430e03bd9b8511176ee56ecd7dadd4e09d7f610b698.b6ca92030167.xlsx"
ft_wholesaler_url = "https://cvf-prod.s3.us-west-2.amazonaws.com/media/documents/47ae571678a1d3fbe67eef4500ac3c1c4ecdafb8d95bf4cfb7a4b8cc27af71a5.ae1b24cd816f.xlsx"
etf_sales_url = "https://cvf-prod.s3.us-west-2.amazonaws.com/media/documents/zsdskvjnbaweilufhawlkjhf.3f723776fd9f.xlsx"
etf_analyzer_url = "https://cvf-prod.s3.us-west-2.amazonaws.com/media/documents/b79e4456533eff69e68aa84446d0bea906308502405d60ce6c9c9a42bb4d0d0a.60914e64f670.xlsx"
uit_sales_url = "https://cvf-prod.s3.us-west-2.amazonaws.com/media/documents/f468eb983edd0dcaa5a0ae66b3fd6835d5d75a0dd74ee6d0ae10ad1f03bdd81f.a1982e4d6e94.xlsx"
buffer_etf_tickers = ['BGLD',
'BUFD',
'BUFG',
'BUFQ',
'BUFR',
'BUFT',
'BUFZ',
'DAPR',
'DAUG',
'DDEC',
'DFEB',
'DJAN',
'DJUL',
'DJUN',
'DMAR',
'DMAY',
'DNOV',
'DOCT',
'DSEP',
'FAPR',
'FAUG',
'FDEC',
'FFEB',
'FJAN',
'FJUL',
'FJUN',
'FMAR',
'FMAY',
'FNOV',
'FOCT',
'FSEP',
'QDEC',
'QJUN',
'QMAR',
'QSPT',
'XDEC',
'XJUN',
'XSEP',
'XMAR',
'XJUL',
'XAUG',
'XSEP',
'XOCT',
'XNOV',
'XDEC',
'YDEC',
'YJUN',
'YMAR',
'YSEP',
'SMAY',
'SAUG',
'SNOV',
'GJAN',
'GFEB',
'GMAR',
'GAPR',
'GMAY',
'GJUN',
'GJUL',
'GAUG',
'GSEP',
'GOCT',
'GNOV',
'GDEC',
'XISE',
'XIDE',]
target_income_etf_tickers = ['KNG','IGLD','RDVI','DOGG','SDVD','TDVI']